---
ytitle: "yuhanwork"
output: html_document
date: "2023-07-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library("Hmisc")
library("PerformanceAnalytics")
library(rstanarm)
library(gam)
library(flexplot)
```

```{r}
setwd("~/Desktop/Rdata-science/cementresearch")
combineold <- read.csv("data/combinedata.csv")

modclink <- lm(Cement ~ Clinker, data = combineold)
summary(modclink)



```
```{r}
setwd("~/Desktop/Rdata-science/cementresearch")
limestonedata <- read.csv("data/limestone2.csv") |>
  mutate(limestone = as.double(str_replace(`limestone.used.ONLY.in.portland..converted.to.Thousand.Metric.Tons.`, ",", ""))) |>
  select(Year, limestone) 



```


```{r}
library(ggplot2)

# Sample time series data with missing values


# Perform linear interpolation to fill in missing values
limemerge$limestone_interp <- approx(limemerge$year, limemerge$limestone, method = "linear", n = length(limemerge$year))$y 


lim
limemerge |>
ggplot(aes(x = year, y = limestone_interp)) +
  geom_line() +
  geom_point()


```

```{r}
rawdata |>
  summarise(project_total = n(), .by = Region) |>
  ggplot(aes(x = Region, y = project_total, fill = Region)) + 
  geom_col()


rawdata |>
  summarise(project_total = n(), .by = Division) |>
  ggplot(aes(x = Division, y = project_total)) + 
  geom_col()

```

Goal: 

X axis: South, West, East, Middle East.....
Y axis: Total number of construction/projects in that region for all years

# Correlation Analysis

```{r warning=FALSE}
setwd("~/Desktop/Rdata-science/cementresearch")
#Import Datasets + Innitial Manipulation

datacpi <- read_csv("data/cpi.csv") |>
   pivot_longer(cols = `1960`:`2022`, 
               names_to = "years",
               values_to = "cpi") |>
  select(c(`Country Name`, years, cpi)) |>
  filter(`Country Name` == "United States") |>
  mutate(year = as.double(years)) |>
  filter(year >= 1968 & year <= 2021)|> # 1960
  select(year, cpi)

setwd("~/Desktop/Rdata-science/cementresearch")
urbanpopdata <- read_csv("data/urbanpop.csv") |>
  filter(`Country Name` == "United States") |>
  pivot_longer(cols = `1960` : `2022`,
               names_to = "year",
               values_to = "urbanpop") |>
  select(year, urbanpop) |>
  filter(year >= 1968 & year <= 2021)
  

dataunemploy <- read_csv("data/unrate.csv") |>
  mutate(unemploy = as.double(UNRATE)) |>
  mutate(year = as.double(str_sub(DATE, 0,4))) |>
  summarise(unemploy = mean(unemploy), .by = year) |>
  filter(year >= 1968 & year <= 2021) # 1960

setwd("~/Desktop/Rdata-science/cementresearch")
housingtot <- read_csv("data/tothouses.csv") |>
  drop_na() |>
  mutate(householdnum = `All households`) |>
  select(Year, householdnum) |>
  arrange(Year) |>
  mutate(new = lag(householdnum)) |>
  mutate(householdnum = householdnum - new)
  



datagdp <- read_csv("data/gdp.csv") |>
   filter(!GDPC1 == ".") |>
  mutate(gdp = as.double(GDPC1)) |>
  mutate(year = as.double(str_sub(DATE, 0,4))) |>
  summarise(gdp = mean(gdp), .by = year) |>
  filter(year >= 1968 & year <= 2021) # 1960


dataoil <- read_csv("data/crudeoilprice.csv") |>
  filter(!WTISPLC == ".") |>
  mutate(oilprice = as.double(WTISPLC)) |>
  mutate(year = as.double(str_sub(DATE, 0,4))) |>
  summarise(oilprice = mean(oilprice), .by = year) |>
  filter(year >= 1968 & year <= 2021) # 1986

setwd("~/Desktop/Rdata-science/cementresearch")
popdata1 <- read.csv("data/POPTHM.csv") |>
  filter(!POPTHM == ".") |>
  mutate(population1 = as.double(POPTHM)) |>
  mutate(year = as.double(str_sub(DATE, 0,4))) |>
  summarise(population1 = mean(population1), .by = year) |>
  filter(year >= 1968 & year <= 2021) 

setwd("~/Desktop/Rdata-science/cementresearch")
popdata2 <- read.csv("data/POPTHM.csv") |>
  filter(!POPTHM == ".") |>
  mutate(population2 = as.double(POPTHM)) |>
  mutate(year = as.double(str_sub(DATE, 0,4))) |>
  summarise(population2 = mean(population2), .by = year) |>
  filter(year >= 1968 & year <= 2021) |> # 1959
  mutate(new = lag(population2)) |>
  mutate(population2 = population2 - new)

setwd("~/Desktop/Rdata-science/cementresearch")
oilconsumpdata <- read_csv("data/oilconsump.csv") |>
  filter(Code == "USA") |>
  mutate(oilconsump = `Oil per capita (kWh)`) |>
  select(Year, oilconsump) |>
  filter(Year >= 1968 & Year <= 2021) 

cementdatastuff <- read.csv("data/cementdatastuff.csv") |>
  mutate(Cement = as.double(Cement)) |>
  mutate(year = Year) |>
  select(year, Cement) |>
   filter(year >= 1968 & year <= 2021)


workersdata <- read.csv("data/workers.csv") |>
  mutate(year = as.double(str_sub(`DATE`, 0, 4)), workers = as.double(str_remove(`USCONS`, ","))) |>
  filter(year >= 1968 & year <= 2021) |>
  select(year, workers) # 1939


housingcomplete <- read.csv("data/housingunit.csv") |>
  mutate(year = Year, housing = as.double(str_remove(`Housing`, ","))) |>
  filter(year >= 1968 & year <= 2021) |>
  select(year, housing) # 1968

setwd("~/Desktop/Rdata-science/cementresearch")
gasdata <- read.csv("data/gasppi.csv") |>
  mutate(year = as.double(str_sub(`DATE`, 0, 4)), gasppi = as.double(str_remove(`WPU0531`, ","))) |>
  select(year, gasppi) |>
  filter(year >= 1968 & year <= 2021) 

setwd("~/Desktop/Rdata-science/cementresearch")
limedata <- read.csv("data/lime.csv") |>
  mutate(year = as.double(Year), lime = as.double(str_remove(`Lime`, ","))) |>
  select(year, lime)

setwd("~/Desktop/Rdata-science/cementresearch")
silicadata <- read.csv("data/silica.csv") |>
  mutate(year = as.double(Year), silica = as.double(str_remove(`Silica`, ","))) |>
  select(year, silica)



```

```{r}
combinedata <- bind_cols(c(datacpi, dataunemploy, datagdp, dataoil, 
                           popdata1, popdata2, cementdatastuff, workersdata, housingcomplete, gasdata,
                           limedata, silicadata, limestonedata, housingtot, urbanpopdata, oilconsumpdata)) |>
  mutate(year = `year...1`) |>
  select(year, cpi, unemploy, gdp, oilprice, 
         population1, population2, Cement, housing, gasppi,
       workers, lime, silica, limestone, householdnum, urbanpop, oilconsump)
setwd("~/Desktop/Rdata-science/cementresearch")
write_csv(combinedata, "data/combinedata10.csv")


```



```{r}


constructspending <- read.csv("data/construct.csv") |>
  mutate(year = as.double(str_sub(`DATE`, 0, 4)), construction = as.double(str_remove(`TLPBLCONS`, ","))) |>
  filter(year >= 1998 & year < 2021) |>
  select(year, construction) # 1993

setwd("~/Desktop/Rdata-science/cementresearch")
limedata <- read.csv("data/lime.csv") |>
  mutate(year = as.double(Year), lime = as.double(str_remove(`Lime`, ","))) |>
  select(year, lime)


silicadata <- read.csv("data/silica.csv") |>
  mutate(year = as.double(Year), silica = as.double(str_remove(`Silica`, ","))) |>
  select(year, silica)



petrodata <- read.csv("data/petrodata.csv") |>
  mutate(year = as.double(str_sub(`DATE`, 0, 4)), petrocoal = as.double(str_remove(`WPU058103`, ","))) |>
  filter(year >= 1998 & year < 2021) |>
  select(year, petrocoal) # 1986




combinedata <- bind_cols(c(datacpi, dataunemploy, datagdp, dataoil, 
                           datacement, popdata, cementprod, cementclinker, 
                           housingcomplete, constructspending, limedata, 
                           gasdata, petrodata, workersdata, silicadata)) |>
  mutate(name = `Country Name...1`, year = `years...2`) |>
  select(name, year, cpi, unemploy, gdp, oilprice, 
         cementppi, population, concreteid, Cement, 
         Clinker, housing, construction, lime, gasppi,
         petrocoal, workers, silica)


setwd("~/Desktop/Rdata-science/cementresearch")
combinedata <- read.csv("data/combinedata3.csv")

```

```{r}

setwd("~/Desktop/Rdata-science/cementresearch")
combinedata <- read.csv("data/combinedata4.csv")
```


```{r}


cordata <- combinedata |>
  mutate(year = as.double(year)) |>
  select(!c(year, lime, silica, gasppi))


cordata2 <- combinedata |>
  mutate(year = as.double(year)) |>
  mutate(unemploy = log10(unemploy), gdp = log10(gdp), oilprice = log10(oilprice), cementppi = log10(cementppi), population = log10(population), concreteid = log10(concreteid), Cement = log10(Cement),
         Clinker = log10(Clinker)) |>
  select(!c(name,year)) 

cormatrix <- rcorr(as.matrix(cordata))

cormatrix$r


```

```{r warning=FALSE}
chart.Correlation(cordata, histogram=TRUE, pch="+")

chart.Correlation(cordata2, histogram=TRUE, pch="+")
```



```{r}
better_corr = function (data, mapping, alignPercent = 0.6, method = "pearson",
                        use = "complete.obs", corAlignPercent = NULL, corMethod = NULL,
                        corUse = NULL, ...)
{
  # for now this is just ggally_cor but gets rid of the ridiculous gridlines and "Corr:"
  require(GGally)
  if (!is.null(corAlignPercent)) {
    stop("'corAlignPercent' is deprecated.  Please use argument 'alignPercent'")
  }
  if (!is.null(corMethod)) {
    stop("'corMethod' is deprecated.  Please use argument 'method'")
  }
  if (!is.null(corUse)) {
    stop("'corUse' is deprecated.  Please use argument 'use'")
  }
  useOptions <- c("all.obs", "complete.obs", "pairwise.complete.obs",
                  "everything", "na.or.complete")
  use <- pmatch(use, useOptions)
  if (is.na(use)) {
    warning("correlation 'use' not found.  Using default value of 'all.obs'")
    use <- useOptions[1]
  }
  else {
    use <- useOptions[use]
  }
  cor_fn <- function(x, y) {
    cor(x, y, method = method, use = use)
  }
  xCol <- deparse(mapping$x)
  yCol <- deparse(mapping$y)
  if (GGally:::is_date(data[[xCol]]) || GGally:::is_date(data[[yCol]])) {
    if (!identical(class(data), "data.frame")) {
      data <- fix_data(data)
    }
    for (col in c(xCol, yCol)) {
      if (GGally:::is_date(data[[col]])) {
        data[[col]] <- as.numeric(data[[col]])
      }
    }
  }
  if (is.numeric(GGally:::eval_data_col(data, mapping$colour))) {
    stop("ggally_cor: mapping color column must be categorical, not numeric")
  }
  colorCol <- deparse(mapping$colour)
  singleColorCol <- ifelse(is.null(colorCol), NULL, paste(colorCol, collapse = ""))
  if (use %in% c("complete.obs", "pairwise.complete.obs", "na.or.complete")) {
    if (length(colorCol) > 0) {
      if (singleColorCol %in% colnames(data)) {
        rows <- complete.cases(data[c(xCol, yCol, colorCol)])
      }
      else {
        rows <- complete.cases(data[c(xCol, yCol)])
      }
    }
    else {
      rows <- complete.cases(data[c(xCol, yCol)])
    }
    if (any(!rows)) {
      total <- sum(!rows)
      if (total > 1) {
        warning("Removed ", total, " rows containing missing values")
      }
      else if (total == 1) {
        warning("Removing 1 row that contained a missing value")
      }
    }
    data <- data[rows, ]
  }
  xVal <- data[[xCol]]
  yVal <- data[[yCol]]
  if (length(names(mapping)) > 0) {
    for (i in length(names(mapping)):1) {
      tmp_map_val <- deparse(mapping[names(mapping)[i]][[1]])
      if (tmp_map_val[length(tmp_map_val)] %in% colnames(data))
        mapping[[names(mapping)[i]]] <- NULL
      if (length(names(mapping)) < 1) {
        mapping <- NULL
        break
      }
    }
  }
  if (length(colorCol) < 1) {
    colorCol <- "ggally_NO_EXIST"
  }
  if ((singleColorCol != "ggally_NO_EXIST") && (singleColorCol %in%
                                                colnames(data))) {
    cord <- ddply(data, c(colorCol), function(x) {
      cor_fn(x[[xCol]], x[[yCol]])
    })
    colnames(cord)[2] <- "ggally_cor"
    cord$ggally_cor <- signif(as.numeric(cord$ggally_cor),
                              3)
    lev <- levels(data[[colorCol]])
    ord <- rep(-1, nrow(cord))
    for (i in 1:nrow(cord)) {
      for (j in seq_along(lev)) {
        if (identical(as.character(cord[i, colorCol]),
                      as.character(lev[j]))) {
          ord[i] <- j
        }
      }
    }
    cord <- cord[order(ord[ord >= 0]), ]
    cord$label <- str_c(cord[[colorCol]], ": ", cord$ggally_cor)
    xmin <- min(xVal, na.rm = TRUE)
    xmax <- max(xVal, na.rm = TRUE)
    xrange <- c(xmin - 0.01 * (xmax - xmin), xmax + 0.01 *
                  (xmax - xmin))
    ymin <- min(yVal, na.rm = TRUE)
    ymax <- max(yVal, na.rm = TRUE)
    yrange <- c(ymin - 0.01 * (ymax - ymin), ymax + 0.01 *
                  (ymax - ymin))
    p <- ggally_text(label = str_c("Cor : ", signif(cor_fn(xVal,
                                                           yVal), 3)), mapping = mapping, xP = 0.5, yP = 0.9,
                     xrange = xrange, yrange = yrange, color = "black",
                     ...) + theme(legend.position = "none")
    xPos <- rep(alignPercent, nrow(cord)) * diff(xrange) +
      min(xrange, na.rm = TRUE)
    yPos <- seq(from = 0.9, to = 0.2, length.out = nrow(cord) +
                  1)
    yPos <- yPos * diff(yrange) + min(yrange, na.rm = TRUE)
    yPos <- yPos[-1]
    cordf <- data.frame(xPos = xPos, yPos = yPos, labelp = cord$label)
    cordf$labelp <- factor(cordf$labelp, levels = cordf$labelp)
    p <- p +
      geom_text(data = cordf, aes(x = xPos, y = yPos, label = labelp, color = labelp), hjust = 1, ...) +
      theme(legend.position = "none",
            panel.grid.major = element_blank())

    p
  }
  else {
    xmin <- min(xVal, na.rm = TRUE)
    xmax <- max(xVal, na.rm = TRUE)
    xrange <- c(xmin - 0.01 * (xmax - xmin), xmax + 0.01 * (xmax - xmin))
    ymin <- min(yVal, na.rm = TRUE)
    ymax <- max(yVal, na.rm = TRUE)
    yrange <- c(ymin - 0.01 * (ymax - ymin), ymax + 0.01 * (ymax - ymin))
    cval = cor_fn(xVal, yVal)
    p <- ggally_text(label = paste(signif(cval, 3), sep = "", collapse = ""),
                     mapping,
                     xP = 0.5,
                     color=I(ifelse(cval>0,
                                    scales::alpha(scales::muted("blue"), alpha=abs(cval)),
                                    scales::alpha(scales::muted("red"), alpha=abs(cval)))),
                     yP = 0.5,
                     xrange = xrange,
                     yrange = yrange, ...) +
      theme(legend.position = "none",
            panel.grid.major = element_blank())
    p
  }
}
```

```{r}
better_smooth <- function(data, mapping, ptcol, ptalpha=1, ptsize=1, linecol, ...) {
  p <- ggplot(data = data, mapping = mapping) +
    geom_point(color=ptcol, alpha=ptalpha, size=ptsize) +
    geom_smooth(color=linecol, ...)
  p
}
```


```{r message=FALSE}
p = GGally::ggpairs(
  cordata[, c(1, 2:9)],
  lower = list(
    continuous = GGally::wrap(
      better_smooth,
      ptalpha = .25,
      ptcol = '#D55E00',
      ptsize = 1,
      linecol = '#03b3ff',
      method = 'loess',
      se = F,
      lwd = .5
    )
  ),
  diag = list(continuous = GGally::wrap(
    'densityDiag', color = 'red', lwd = .5
  )),
  # upper=list(continuous=GGally::wrap(better_corr)),
  axisLabels = "none"
)

p
```




```{r}
# Load necessary libraries
library(tidyverse)
library(car)
library(plotly)
library(leaps)
library(lmtest)
library(margins)
library(mgcv)
library(rstanarm)
library(palmerpenguins)
library(vars)




setwd("~/Desktop/Rdata-science/cementresearch")
combinedata4 <- read.csv("data/combinedata5.csv")


combinedata <- read.csv("data/combinedata6.csv")


combinedata2 <- combinedata |>
  select(!c(lime, silica, gasppi))

# Load your dataset (assuming your data is in a dataframe called 'data')
# Make sure your data includes columns for the dependent variable and predictor variables

# Filter out data points affected by the housing crisis (e.g., 2008-2009)
data_filtered <- combinedata2 |>
  drop_na() |>
  select(!c(year,limestone))

# Perform stepwise regression on the filtered data
stepwise_model <- step(lm(formula = Cement ~ ., family = gaussian, data = data_filtered), 
                          direction = c("backward"), k = log(54))

# glm_model <- stan_glm(formula = Cement ~ unemploy + gdp + workers + limestone, data = data_filtered, 
#                       iter = 5000)
# Print the results of the stepwise regression
summary(stepwise_model)
bptest(stepwise_model)

# Check assumptions and diagnostic tests for the final model
# For example, you can use the 'car' package for diagnostic tests
# You can also visualize the residuals to assess model performance

residuals <- resid(stepwise_model)

par(mfrow = c(2,2))
plot(stepwise_model, which = 1) 
plot(stepwise_model, which = 2)
plot(stepwise_model, which = 3) 
plot(stepwise_model, which = 5)

resdulpdf<-density(stepwise_model$residuals)
plot(resdulpdf,main='Residual pdf shape Plot',xlab='Residuals')


resdulcdf <- ecdf(stepwise_model$residuals)
par(mfrow = c(1,2))
plot(resdulpdf,main='Residual pdf shape Plot',xlab='Residuals')
plot(resdulcdf,main='Residuals cdf ',xlab='Residuals')

plot(stepwise_model, which = 4)


vif(stepwise_model)
#unemploy
unemploytest = -1.043e+03*(3.7) # 3-7%, 3.7%

#gdp
gdptest = 7.934e-01*(36779)
  7.934e-01*(32119.290) # 32119.290

#housing
housingtest = 1.009e+01*(812)
  1.009e+01*(1286.9 * 1.01126^29) # 

#limestone
limestonetest = 3.922e-01*(163610)
  3.922e-01*(112960*1.03*1.03*1.03*1.03*1.03) # 


unemploytest + gdptest + housingtest + limestonetest + 2.465e+04

datavariables <- data_filtered |>
  select(Cement, unemploy, gdp, housing)

# Assuming your factors are in a data frame or matrix named 'factors'
result_johansen <- ca.jo(datavariables, type = "trace", K = 4)  # Adjust K as needed

# Print the results
summary(result_johansen)


```

```{r}
corchartfinal <- combinedata |>
  select(Cement, unemploy, gdp, housing)

chart.Correlation(corchartfinal, histogram=TRUE, pch="+")
```




#Using Stan_GLM to Predict instead of researching paper

```{r}
#Housing Rate
housingrate <- combinedata |>
  select(year, housing) |>
  mutate(housinglag = lag(housing)) |>
  drop_na() |>
  mutate(rate = housing/housinglag) |>
  filter(!(year %in% c(2020, 2008, 2009, 2010, 2002, 1991, 1982, 
                       1981, 1975, 1974, 1971, 1980, 1982, 2007, 1983))) 


housingrate |>
  ggplot(aes(x = year, y = rate)) + 
  geom_point()

modelhouse <- stan_glm(rate ~ 1, data = housingrate, refresh = 0)

pphouse <- posterior_epred(modelhouse, newdata = tibble(rate = "")) |>
  as_tibble() 

mean(pphouse$`1`)

pphouse |>
  ggplot(aes(x = `1`)) + 
  geom_density()


# Limestone

limestonerate <- combinedata |>
  select(year, limestone) |>
  mutate(limestonelag = lag(limestone)) |>
  drop_na() |>
  mutate(rate = limestone/limestonelag) |>
  filter(!(year %in% c(2020, 2008, 2009, 2010, 2002, 1991, 1982, 
                       1981, 1975, 1974, 1971, 1980, 1982, 2007))) 

limestonerate |>
  ggplot(aes(x = year, y = rate)) + 
  geom_point()

modellimestone <- stan_glm(rate ~ 1, data = limestonerate, refresh = 0)

pplimestone <- posterior_epred(modellimestone, newdata = tibble(rate = "")) |>
  as_tibble() 

mean(pplimestone$`1`)

pplimestone |>
  ggplot(aes(x = `1`)) + 
  geom_density()
```


```{r}
model1 <- stan_glm(formula = Cement ~ unemploy + gdp + housing + limestone, data = data_filtered, 
                   refresh = 0, chains = 6, iter = 5000)


pp <- posterior_predict(model1, newdata = tibble(unemploy = 3, gdp = 36779.404, 
                                                 housing = 812.2324, limestone = 163610.0)) |>
  as_tibble() |>
  pivot_longer(cols = `1` : `1`,
               names_to = 'unemployrate',
               values_to = 'predict')

pp |>
  ggplot(aes(x = predict, fill = unemployrate)) +
  geom_density(color = 'black', alpha = 0.4)

mean(pp$predict)
```

```{r}
combinedata2 |>
  ggplot(aes(x = year, y = limestone)) + 
  geom_line()
```




```{r}
standardized_model <- lm(formula = scale(Cement) ~ scale(unemploy) + scale(gdp) + 
                           scale(housing) + scale(limestone),
    data = data_filtered)
summary(standardized_model)


residuals2 <- resid(standardized_model)
plot(standardized_model, which = 1) 
plot(standardized_model, which = 2)
plot(standardized_model, which = 3) 


bptest(standardized_model)

resdulpdf2<-density(standardized_model$residuals)
plot(resdulpdf,main='Residual pdf shape Plot',xlab='Residuals')

plot(standardized_model, which = 4)
plot(standardized_model, which = 5)





```


# Cross Validation


```{r}
library(caret)
ctrl <- trainControl(method = "cv",  # Cross-validation method (e.g., "cv" for k-fold)
                     number = 5,     # Number of folds
                     savePredictions = TRUE) 

model <- train(Cement ~ unemploy + oilprice + construction + lime,
               data = data_filtered,
               method = "lm",       # Specify the modeling method (linear regression)
               trControl = ctrl) 

plot(model, which = 2)

```


```{r}
library(mgcv)
library(lme4)  # For mixed-effects models (optional)
library(MASS)

model <- rlm(Cement ~ unemploy + oilprice + construction + lime, data = data_filtered)


summary(model)
```


```{r}
library(margins)
```



