```{r}
library(tidyverse)
library(vars)
library(here)
library(devtools)
library(ggplot2)
library(forecast)
library(tseries)
library(urca)
library(TTR)
```

## Loading the data set

```{r}
setwd("C:/Users/User/Desktop/R_Data_Science/cementresearch/")
df <- read_csv("data/combinedata2.csv")

df_ts <- ts(df |> dplyr::select(!year), start = 1968, frequency = 1) #convert df tibble into a time series from 1998 to 2020


setwd("C:/Users/User/Desktop/R_Data_Science/cementresearch/")
gdp_annual_percent <- read_csv("data/gdp_annual_percent.csv") #https://fred.stlouisfed.org/series/A191RL1Q225SBEA

## Don't know if using this yet 

```

# After new data set including 1968 - 2021

VARS: cpi, unemploy, gdp, oilprice, population, Cement, housing, gasppi, workers

```{r}

# ------- CPI ---------

adf.test(df$cpi) #not stationary
adf.test(diff(df$cpi)) #1st order difference -> becomes stationary

# ------- unemploy ---------

adf.test(df$unemploy) #not stationary
adf.test(diff(df$unemploy)) 

# ------- GDP ---------

adf.test(df$gdp) # not stationary
adf.test(diff(df$gdp)) #1st order difference -> becomes stationary


# ------- oilprice ---------

adf.test(df$oilprice) # not stationary
adf.test(diff(df$oilprice)) #1st order difference -> becomes stationary

# ------- population ---------

adf.test(df$population) # not stationary
adf.test(diff(df$population,differences = 3)) #3rd order difference -> becomes stationary

plot.ts(ts(diff(df$population,differences = 3), start = 1968, frequency = 1))

# ------- Cement ---------

adf.test(df$Cement)# not stationary
adf.test(diff(df$Cement)) #1st order dif -> becomes stationary

# ------- housing ---------

adf.test(df$housing) # not stationary
adf.test(diff(df$housing)) #1st order dif -> becomes stationary

# ------- gasppi ---------

adf.test(df$gasppi) # not stationary
adf.test(diff(df$gasppi,differences = 2)) #2nd order dif -> becomes stationary

# ------- workers ---------

adf.test(df$workers) # not stationary
adf.test(diff(df$workers)) #2nd order dif -> becomes stationary

# ----------------------

# --------- TESTING WITH ALL VARIABLES -----------

diff_1_vars <- df[,c("cpi","unemploy","oilprice","Cement","housing","workers", "gdp")]

diff_1_vars <- ts(diff_1_vars, start = 1968, frequency = 1)
diff_1_vars <- lapply(diff_1_vars,function(x) diff(x))


diff_2_vars <- diff(ts(df$gasppi, start = 1968, frequency = 1),differences = 2)
diff_3_vars <- diff(ts(df$population,start = 1968, frequency = 1),differences = 3)

max_start <- max(start(diff_1_vars), start(diff_2_vars), start(diff_3_vars))
differenced_df <- cbind(
  as.data.frame(lapply(diff_1_vars, function(x) window(x, start = max_start))), 
  as.data.frame(window(diff_2_vars,start = max_start)),
  as.data.frame(window(diff_3_vars,start = max_start))
)

# renaming the last two columns gasppi (2nd to last) and population (last)
current_colnames <- colnames(differenced_df)
current_colnames[(length(current_colnames) - 1):length(current_colnames)] <- c("gasppi", "population")
colnames(differenced_df) <- current_colnames

# turning it back into a time series format (this is in rates)
differenced_df <- ts(differenced_df, start = max_start, frequency = 1)


## --- Affirming that all variables are now stationary ---- POSITIVE

adf_results <- lapply(differenced_df, function(variable) {
  adf_result <- adf.test(variable)
  return(adf_result)
})

for (i in seq_along(adf_results)) {
  variable_name <- names(differenced_df)[i]
  p_value <- adf_results[[i]]$p.value
  stationary_status <- ifelse(p_value < 0.05, "Stationary", "Non-Stationary")
  
  cat("Variable:", variable_name, "\n")
  cat("P-Value:", p_value, "\n")
  cat("Status:", stationary_status, "\n\n")
}

```

## VAR STUFF

```{r}

dummy_var <- data.frame(year = max_start:2021) |>
  mutate(value = case_when(year %in% c(2008,2009) ~ 1,TRUE ~ 0))

dummy_var <- ts(dummy_var[,-1],start = max_start, frequency = 1)
merged_data <- cbind(differenced_df,dummy_var)

optimal_lag <- VARselect(merged_data,lag.max = 10) #gives AIC of 5, which is interesting...
optimal_lag <- optimal_lag$selection[1]
var_model <- VAR(merged_data, p = 1, type = "none")

years_ahead <- 29
forecast <- predict(var_model, n.ahead = years_ahead)
par(mar = c(1, 1, 1, 1))
plot(forecast)


```

## Plotting Results
```{r}

forecast_original <- cumsum(forecast$fcst$differenced_df.Cement[,1]) + df$Cement[length(df$Cement)]#the original value in 1968

df1 <- data.frame(df$Cement)
colnames(df1) <- "cement"
df2 <- data.frame(forecast_original)
colnames(df2) <- "cement"

merged_temp <- rbind(df1, df2)
years_temp <- data.frame(1968:(2021+years_ahead))
colnames(years_temp) <- "years"

plot_final <- cbind(years_temp,merged_temp)

plot_final |>
  ggplot(aes(x = years, y = cement)) + 
  geom_line() + 
  geom_vline(xintercept = 2021, color = "red", linetype = "dashed") + 
  xlab("Years") + ylab("Cement (million metric tons)") +
  scale_y_continuous(labels = scales::comma_format(scale = 1e-3))
```



## Testing with limited variables filtered based on correlation distrubtion matrix (to prevent cross-validation)
```{r}
# --------- TESTING WITH LIMITED VARIABLES ----------- cpi, housing, gdp , Cement, oilprice, gasppi

diff_1_vars_lim <- df[,c("cpi","oilprice","Cement","housing","gdp")]
diff_1_vars_lim <- ts(diff_1_vars_lim, start = 1968, frequency = 1)
diff_1_vars_lim <- lapply(diff_1_vars_lim,function(x) diff(x))
diff_2_vars_lim <- diff(ts(df$gasppi, start = 1968, frequency = 1),differences = 2)

differenced_df_lim <- cbind(
  as.data.frame(lapply(diff_1_vars_lim, function(x) window(x, start = 1970))), 
  as.data.frame(window(diff_2_vars_lim,start = 1970)) #gasppi
)

differenced_df_lim <- ts(differenced_df_lim, start = 1970, frequency = 1)

optimal_lag_lim <- VARselect(differenced_df_lim,lag.max = 10) #gives AIC of 5, which is interesting...
# optimal_lag_lim <- optimal_lag$selection[1]
var_model_lim <- VAR(differenced_df_lim, p = 1, type = "const")

forecast_lim <- predict(var_model_lim, n.ahead = 20)
par(mar = c(1, 1, 1, 1))
plot(forecast_lim)

forecast_original_lim <- cumsum(forecast_lim$fcst$Cement[,1]) + df$Cement[length(df$Cement)]#the original value in 1968
# forecast_original_lim_lower_upper <-apply(forecast_lim$fcst$Cement[,2:3],2,cumsum) + df$Cement[length(df$Cement)]

df1 <- data.frame(df$Cement)
colnames(df1) <- "cement"
df2 <- data.frame(forecast_original_lim)
colnames(df2) <- "cement"

merged_df_lim <- rbind(df1, df2)
years_lim <- data.frame(1968:2041)
colnames(years_lim) <- "years"

plot_lim <- cbind(years_lim,merged_df_lim)

plot_lim |>
  ggplot(aes(x = years, y = cement)) + 
  geom_line() + 
  geom_vline(xintercept = 2021, color = "red", linetype = "dashed") + 
  xlab("Years") + ylab("Cement (million metric tons)") +
  scale_y_continuous(labels = scales::comma_format(scale = 1e-3))


```


## Model Diagnosis
```{r}
serial_test <- serial.test(var_model, lags.pt = optimal_lag) #passes this test because p-value > 0.05 (yes i meant to type greater)
normality_test <- normality.test(var_model) #
arch_test <- arch.test(var_model)

diagnosis_df <- as.data.frame(differenced_df)

for (col in colnames(diagnosis_df)) {
  acf_plot <- Acf(diagnosis_df[[col]], main = paste("ACF -", col))
  pacf_plot <- Pacf(diagnosis_df[[col]], main = paste("PACF -", col))
}
```


